contact_links:
  - about: Ask a question or request support here
    name: Ask for Support
    url: >-
      https://github.com/Maize-Network/maize-blockchain/discussions/new?category=support
  - about: Request a new feature or idea here
    name: Make a Request
    url: >-
      https://github.com/Maize-Network/maize-blockchain/discussions/new?category=ideas
  - about: Get support on the Maize Discord chat channels.
    name: Join the Discord support chat
    url: 'https://discord.gg/2whh7ygat9'
